[[constraint]]
  name = "github.com/golang/snappy"
  version = "0.0.1"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.3"

[prune]
  go-tests = true
  unused-packages = true
